[pytest]
pythonpath = src

markers =
    unit: run unit tests
    integration: run integration tests
    task1: run tests for weekly task 1 (Diskussion)
    task2: run tests for weekly task 2 (Anmälningar)
    task3: run tests for weekly task 3 (Kundvagn)
    task4: run tests for weekly task 4 (Spårbara transaktioner)
