[pytest]
pythonpath = src

markers =
    unit: run unit tests
    integration: run integration tests
    task2: run tests for weekly task 2 (Anmälningar)
    task3: run tests for weekly task 3 (Kundvagn)
